version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=camera_store
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin123
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - 8080:80
    depends_on:
      - mysql